---
title: "BS_HW3_GerasimovIV"
output: html_document
---


```{r load_libraries, include=TRUE}

library(readxl)
library(dplyr)
library(ggplot2)
library(tidyverse)
```

```{r load, include=TRUE}
pima <- read_excel("pima.xlsx")
head(pima)
```
```{r omits_deleting, include=TRUE}
# omits deleting
pima <- na.omit(pima)
```

Задание 1.

```{r description_statistics, include=TRUE}

# Calculating descriptive statistics for glucose
glucose_stats <- summary(pima$glucose)
cat("Descriptive statistics for glucose:\n")
print(glucose_stats)

# Calculating descriptive statistics for pressure
pressure_stats <- summary(pima$pressure)
cat("\nDescriptive statistics for pressure:\n")
print(pressure_stats)

# Calculating descriptive statistics for mass
mass_stats <- summary(pima$mass)
cat("\nDescriptive statistics for mass:\n")
print(mass_stats)
```

Задание 2.
```{r description_statistics_in_diabets, include=TRUE}

# Descriptive statistics for the diabetes variable
diabetes_stats <- table(pima$diabetes)
diabetes_stats_relative <- prop.table(diabetes_stats)
cat("Descriptive statistics for diabetes:\n")
print(diabetes_stats)
cat("\nrelative descriptive statistics for diabetes:\n")
print( diabetes_stats_relative)

```
```{r description_statistics_in_age_groups, include=TRUE}

# Creating the age_group variable
pima <- pima %>%
  mutate(age_group = case_when(
    age >= 21 & age <= 35 ~ "21-35",
    age >= 36 & age <= 49 ~ "36-49",
    age >= 50 ~ "50+",
  ))

# Calculate absolute and relative descriptive statistics for the age_group variable
age_group_table <- table(pima$age_group)
age_group_relative <- prop.table(age_group_table)
cat("\nDescriptive statistics for age_group:\n")
print(age_group_table)
cat("\nrelative descriptive statistics for age_group:\n")
print(age_group_relative)
```
Задание 3.

```{r pedigree_confidence_interval, include=TRUE}

# Calculate the mean and standard deviation
mean_pedigree <- mean(pima$pedigree, na.rm = TRUE)
sd_pedigree <- sd(pima$pedigree, na.rm = TRUE)
n_pedigree <- sum(!is.na(pima$pedigree))

# Determine the z-score for a 90% confidence interval
z_score <- qnorm(0.95)  # 0.95 because we look at the one side

# Calculate the margin of error
margin_error <- z_score * (sd_pedigree / sqrt(n_pedigree))

# Calculate the confidence interval
ci_lower <- mean_pedigree - margin_error
ci_upper <- mean_pedigree + margin_error

cat("90% Confidence interval for the pedigree variable:\n [", ci_lower, ", ", ci_upper, "]", sep = "")
```
Задание 4.

```{r glucose_exploration, include=TRUE}

# Distribution graph for the glucose variable with the average value estimated marked for both 'pos' and 'neg' groups

# Overally
ggplot(pima, aes(x = glucose)) +
  geom_density(fill = "gray", alpha = 0.5) +
  geom_vline(aes(xintercept = mean(glucose, na.rm = TRUE)), color = "green", linewidth = 1) +
  ggtitle("Glucose level distribution with mean value overally") +
  xlab("Glucose") +
  ylab("Density")

# By diabetes status
ggplot(pima, aes(x = glucose, fill = diabetes)) +
  geom_density(alpha = 0.5) +
  geom_vline(data = subset(pima, diabetes == 'pos'), aes(xintercept = mean(glucose, na.rm = TRUE)), color = "red", linewidth = 1) +
  geom_vline(data = subset(pima, diabetes == 'neg'), aes(xintercept = mean(glucose, na.rm = TRUE)), color = "blue",  linewidth = 1) +
  scale_fill_manual(values = c("pos" = "red", "neg" = "blue")) +
  ggtitle("Glucose level distribution with mean values for diabetes status") +
  xlab("Glucose") +
  ylab("Density")

# Histogram for the glucose variable

ggplot(pima, aes(x = glucose)) +
  geom_histogram(binwidth = 10, fill = "gray", color = "black") +
  geom_vline(aes(xintercept = mean(glucose, na.rm = TRUE)), color = "green", linewidth = 1) +
  ggtitle("Histogram of glucose levels") +
  xlab("Glucose") +
  ylab("Count")

# Box plots for the glucose variable based on diabetes status

ggplot(pima, aes(x = diabetes, y = glucose, fill = diabetes))+
  geom_boxplot() +
  scale_fill_manual(values = c("pos" = "red", "neg" = "blue")) +
  ggtitle("Box-plot of glucose levels by diabetes status") +
  xlab("Diabetes status") +
  ylab("Glucose")
```

Задание 5.

```{r triceps_body_mass, include=TRUE}

# Scatter plot showing the relationship between triceps and body mass, colored and grouped by diabetes status

# On the separate fields

ggplot(pima, aes(x = triceps, y = mass)) +
  geom_point(aes(color = diabetes)) +
  facet_grid(~diabetes) +
  ggtitle("Scatter plot of triceps from body mass index by diabetes status") +
  xlab("Triceps thickness") +
  ylab("Body mass index") +
  scale_color_manual(values = c("pos" = "red", "neg" = "blue"))  # Assigning custom colors

# On the single field

ggplot(pima, aes(x = triceps, y = mass, color = diabetes)) +
  geom_point() +
  ggtitle("Scatter plot of triceps from body mass index by diabetes status") +
  xlab("Triceps thickness") +
  ylab("Body mass index") +
  scale_color_manual(values = c("pos" = "red", "neg" = "blue"))  # Assigning custom colors

```


